### PR TITLE
Remove strict version requirements to resolve conflicts with other packages

### PR DESCRIPTION
**Pull request by brian-dlee**

### CODE REVIEW

**Comment by samims** [comment]
I think that can cause issue near future. It's better to have a version which is supported by other libs as well as pyrebase

**Comment by ukch** [comment]
@brian-dlee why did you close this? :cry:

**Comment by brian-dlee** [comment]
@ukch unfortunately it's been open for over a year with no activity, so I finally decided to just close it. It appears this repo is just not maintained anymore

**Comment by ukch** [comment]
@brian-dlee FYI there is a maintained version of pyrebase on PyPI under the name 'pyrebase5'. I am using that now, since your fork is no longer available...

**Pull request closed without merging**
